### ISSUE TITLE
Rebuild question

### ISSUE THREAD

**Issue by bentrynning** [STUkh/gatsby-strapi-docker#1]
Hi @STUkh  

Im using your setup as inspiration for my own project. 
My question is how is your setup handling changes in strapi to be reflected in gatsby after an update in strapi is done ? 

Do you manually rebuild gatsby on your server or is there a update mechanism some where that i dont see :) 

Best regards
Bent

**Comment by STUkh** [comment]
Hi @bentrynning, sorry for delayed answer. You can create your own simple hook server, or use 3rd party services like netlify. I prefer first option 😉

**Comment by bentrynning** [comment]
Thanks for det reply, do you know of any hook server examples? Otherwise I try to search for one. Have a great week!

**Comment by bentrynning** [comment]
Thanks for det reply, do you know of any hook server examples? Otherwise I try to search for one. Have a great week!
